services:
  postgres:
    image: postgres:16-alpine
    container_name: juanmacrypto-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: juanmacrypto
    ports:
      - '5432:5432'
    volumes:
      - juanmacrypto-pgdata:/var/lib/postgresql/data

volumes:
  juanmacrypto-pgdata:
